# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

development:
  price_ingest_daily:
    class: PriceIngestJob
    schedule: every day at 6:30pm America/Los_Angeles
  metric_compute_daily:
    class: MetricComputeJob
    schedule: every day at 7:00pm America/Los_Angeles

  price_ingest_intraday:
    class: PriceIngestJob
    schedule: every hour

  metric_compute_intraday:
    class: MetricComputeJob
    schedule: every hour

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  price_ingest_daily:
    class: PriceIngestJob
    schedule: every day at 6:30pm America/Los_Angeles
  metric_compute_daily:
    class: MetricComputeJob
    schedule: every day at 7:00pm America/Los_Angeles

  price_ingest_intraday:
    class: PriceIngestJob
    schedule: every hour at minute 10

  metric_compute_intraday:
    class: MetricComputeJob
    schedule: every hour at minute 20
